workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"
    scripts:
      - name: Install dependencies
        script: |
          chmod +x $GRADLEW_PATH
          $GRADLEW_PATH dependencies
      - name: Build APK
        script: |
          $GRADLEW_PATH assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - ventunes@gmail.com
